"""initial_schema_20251127_202700

Revision ID: 45452173f76c
Revises: 
Create Date: 2025-11-27 20:27:01.670396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45452173f76c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scan_summaries')
    op.drop_index('idx_reports_scan', table_name='reports')
    op.drop_table('reports')
    op.drop_index('idx_raw_scan_results_scan_tool', table_name='raw_scan_results')
    op.drop_table('raw_scan_results')
    op.drop_table('scan_history')
    op.drop_index('ix_parsed_scan_results_scan_id', table_name='parsed_scan_results')
    op.drop_table('parsed_scan_results')
    op.alter_column('feed_entries', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('feed_entries', 'feed_source',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Source of the feed: nvd, exploitdb, etc.',
               existing_nullable=False)
    op.alter_column('feed_entries', 'entry_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Unique identifier from source: CVE-2024-1234, EDB-12345, etc.',
               existing_nullable=False)
    op.alter_column('feed_entries', 'affected_products',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True)
    op.alter_column('feed_entries', 'cwe_ids',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True)
    op.alter_column('feed_entries', 'ref_urls',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True)
    op.alter_column('feed_entries', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment=None,
               existing_comment='Additional flexible metadata in JSON format',
               existing_nullable=True)
    op.alter_column('feed_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('feed_entries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_feed_source', table_name='feed_entries')
    op.drop_index('idx_unique_entry_id', table_name='feed_entries')
    op.create_index(op.f('ix_feed_entries_entry_id'), 'feed_entries', ['entry_id'], unique=False)
    op.create_index(op.f('ix_feed_entries_feed_source'), 'feed_entries', ['feed_source'], unique=False)
    op.create_index(op.f('ix_feed_entries_published_date'), 'feed_entries', ['published_date'], unique=False)
    op.drop_table_comment(
        'feed_entries',
        existing_comment='Threat intelligence feed entries from NVD, ExploitDB, and other sources',
        schema=None
    )
    op.alter_column('scans', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('scans', 'priority',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('scans', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('scans', 'options',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('scans', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('idx_scans_archived', table_name='scans')
    op.drop_index('idx_scans_completed_at', table_name='scans')
    op.drop_index('idx_scans_created', table_name='scans')
    op.drop_index('idx_scans_status', table_name='scans')
    op.drop_index('idx_scans_status_priority', table_name='scans')
    op.drop_index('idx_scans_tool', table_name='scans')
    op.drop_column('scans', 'archived_at')
    op.drop_column('scans', 'retention_days')
    op.drop_column('scans', 'progress')
    op.drop_column('scans', 'version')
    op.drop_column('scans', 'archived')
    op.alter_column('vulnerabilities', 'vuln_id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('vulnerabilities', 'references',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True)
    op.alter_column('vulnerabilities', 'discovered_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('vulnerabilities', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('idx_vulnerabilities_cve_id', table_name='vulnerabilities', postgresql_where='(cve_id IS NOT NULL)')
    op.drop_index('idx_vulnerabilities_cvss_score', table_name='vulnerabilities')
    op.drop_index('idx_vulnerabilities_port', table_name='vulnerabilities', postgresql_where='(port IS NOT NULL)')
    op.drop_index('idx_vulnerabilities_scan_discovered', table_name='vulnerabilities')
    op.drop_index('idx_vulnerabilities_service', table_name='vulnerabilities', postgresql_where='(service IS NOT NULL)')
    op.drop_index('idx_vulnerabilities_severity', table_name='vulnerabilities')
    op.drop_index('idx_vulns_scan', table_name='vulnerabilities')
    op.drop_index('idx_vulns_severity', table_name='vulnerabilities')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_vulns_severity', 'vulnerabilities', ['severity'], unique=False)
    op.create_index('idx_vulns_scan', 'vulnerabilities', ['scan_id'], unique=False)
    op.create_index('idx_vulnerabilities_severity', 'vulnerabilities', ['severity'], unique=False)
    op.create_index('idx_vulnerabilities_service', 'vulnerabilities', ['service'], unique=False, postgresql_where='(service IS NOT NULL)')
    op.create_index('idx_vulnerabilities_scan_discovered', 'vulnerabilities', ['scan_id', sa.text('discovered_at DESC')], unique=False)
    op.create_index('idx_vulnerabilities_port', 'vulnerabilities', ['port'], unique=False, postgresql_where='(port IS NOT NULL)')
    op.create_index('idx_vulnerabilities_cvss_score', 'vulnerabilities', [sa.text('cvss_score DESC')], unique=False)
    op.create_index('idx_vulnerabilities_cve_id', 'vulnerabilities', ['cve_id'], unique=False, postgresql_where='(cve_id IS NOT NULL)')
    op.alter_column('vulnerabilities', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('vulnerabilities', 'discovered_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('vulnerabilities', 'references',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('vulnerabilities', 'vuln_id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.add_column('scans', sa.Column('archived', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('scans', sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.add_column('scans', sa.Column('progress', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('scans', sa.Column('retention_days', sa.INTEGER(), server_default=sa.text('90'), autoincrement=False, nullable=True))
    op.add_column('scans', sa.Column('archived_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('idx_scans_tool', 'scans', ['tool_name'], unique=False)
    op.create_index('idx_scans_status_priority', 'scans', ['status', sa.text('priority DESC')], unique=False)
    op.create_index('idx_scans_status', 'scans', ['status'], unique=False)
    op.create_index('idx_scans_created', 'scans', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_scans_completed_at', 'scans', [sa.text('completed_at DESC')], unique=False)
    op.create_index('idx_scans_archived', 'scans', ['archived', 'archived_at'], unique=False)
    op.alter_column('scans', 'tags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('scans', 'options',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('scans', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('scans', 'priority',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'medium'::character varying"),
               existing_nullable=True)
    op.alter_column('scans', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=True)
    op.create_table_comment(
        'feed_entries',
        'Threat intelligence feed entries from NVD, ExploitDB, and other sources',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_feed_entries_published_date'), table_name='feed_entries')
    op.drop_index(op.f('ix_feed_entries_feed_source'), table_name='feed_entries')
    op.drop_index(op.f('ix_feed_entries_entry_id'), table_name='feed_entries')
    op.create_index('idx_unique_entry_id', 'feed_entries', ['entry_id'], unique=False)
    op.create_index('idx_feed_source', 'feed_entries', ['feed_source'], unique=False)
    op.alter_column('feed_entries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('feed_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('feed_entries', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment='Additional flexible metadata in JSON format',
               existing_nullable=True)
    op.alter_column('feed_entries', 'ref_urls',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('feed_entries', 'cwe_ids',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('feed_entries', 'affected_products',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('feed_entries', 'entry_id',
               existing_type=sa.VARCHAR(length=100),
               comment='Unique identifier from source: CVE-2024-1234, EDB-12345, etc.',
               existing_nullable=False)
    op.alter_column('feed_entries', 'feed_source',
               existing_type=sa.VARCHAR(length=50),
               comment='Source of the feed: nvd, exploitdb, etc.',
               existing_nullable=False)
    op.alter_column('feed_entries', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_table('parsed_scan_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('tool_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('parsed_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name='parsed_scan_results_scan_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='parsed_scan_results_pkey')
    )
    op.create_index('ix_parsed_scan_results_scan_id', 'parsed_scan_results', ['scan_id'], unique=False)
    op.create_table('scan_history',
    sa.Column('history_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('scan_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name='scan_history_scan_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('history_id', name='scan_history_pkey')
    )
    op.create_table('raw_scan_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('tool_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('raw_output', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('output_format', sa.VARCHAR(length=20), server_default=sa.text("'text'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name='raw_scan_results_scan_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='raw_scan_results_pkey')
    )
    op.create_index('idx_raw_scan_results_scan_tool', 'raw_scan_results', ['scan_id', 'tool_name'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('scan_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('format', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('filepath', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('options', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name='reports_scan_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='reports_pkey')
    )
    op.create_index('idx_reports_scan', 'reports', ['scan_id'], unique=False)
    op.create_table('scan_summaries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('total_hosts', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('total_ports', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('total_vulnerabilities', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('critical_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('high_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('medium_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('low_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('info_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('ai_summary', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name='scan_summaries_scan_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='scan_summaries_pkey'),
    sa.UniqueConstraint('scan_id', name='scan_summaries_scan_id_key')
    )
    # ### end Alembic commands ###
